### ISSUE TITLE
训练结果相关问题

### ISSUE THREAD

**Issue by ZWXCV** [Qinying-Liu/CASE#1]
您好，在执行训练指令后，显示的best_map结果与论文展示结果相差2.0左右，请问有什么方法可以复现您论文中的结果呢？期待作者的回复，谢谢

**Comment by Qinying-Liu** [comment]
Hi, 我不太清楚你环境配置。我这边的环境配置是python 3.6.2和torch 1.7.0，你可以试试这种环境配置。

**Comment by ZWXCV** [comment]
问题已解决，感谢您的回复

**Comment by Lcode119** [comment]
> 问题已解决，感谢您的回复
请问你是怎么解决这个问题的，显示的best_map结果与论文展示结果也是相差2.0左右
