### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by EmreOzkose** [Qinying-Liu/CASE#3]
Hi, congrats for the work. 

Can you share a feature extraction script for testing our own videos?

**Comment by Qinying-Liu** [comment]
I am sorry. We use pre-processed features of the benchmark datasets provided by other methods and don't have feature extraction script. You may refer to https://github.com/piergiaj/pytorch-i3d.

**Comment by EmreOzkose** [comment]
[pytorch-i3d](https://github.com/piergiaj/pytorch-i3d) repo is really hard to reproduce :). Anyway, thank you for reply
